repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: [--enforce-all, --maxkb=100]
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: require-ascii
      - id: script-must-have-extension
      - id: forbid-binary
        exclude: docs/source/_static/.*.png
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: forbid-crlf
      - id: forbid-tabs
  - repo: https://github.com/streetsidesoftware/cspell-cli
    rev: v8.17.0
    hooks:
      - id: cspell
        exclude: \.gitignore|.*\.properties
  - repo: https://github.com/pycqa/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        args: [--max-line-length=150]
        exclude: docs/source/conf.py
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        additional_dependencies: ["tomli"]
        exclude: examples|tests|conf.py
  - repo: https://github.com/regebro/pyroma
    rev: f4ef6995f6c054586fe6d5d33d180abe71ebabd0
    hooks:
    - id: pyroma
      args: ["-d", "--min=10", ".", "--skip-tests", "ValidREST"]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.14.1
    hooks:
      - id: mypy
        additional_dependencies: ["types-docutils", "types-python-dateutil", "types-requests"]
  - repo: https://github.com/johannsdg/pre-commit-license-headers
    rev: d53087d331942f263cb553dc67b0e51ffa3a3481
    hooks:
      - id: check-license-headers
        types: [python]
        args:
          - --template
          - (C) Crown Copyright [OWNER]
          - --owner=GCHQ
